# Generated by Django 4.2.13 on 2026-02-25 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('Ouvert', 'Ouvert'), ('En cours', 'En cours'), ('Résolu', 'Résolu'), ('Fermé', 'Fermé')], db_index=True, default='Ouvert', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('Compte bloqué', 'Compte bloqué'), ('Salle / Équipement', 'Salle / Équipement'), ('Matériel informatique', 'Matériel informatique'), ('Télécommandes de climatiseur', 'Télécommandes de climatiseur')], db_index=True, max_length=50, null=True)),
                ('priority_score', models.CharField(blank=True, choices=[('Faible', 'Faible'), ('Moyen', 'Moyen'), ('Élevé', 'Élevé'), ('Critique', 'Critique')], db_index=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tickets',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'priority_score'], name='tickets_status_354e9c_idx'), models.Index(fields=['created_by', 'status'], name='tickets_created_2f39d7_idx')],
            },
        ),
    ]
